version: "2.15"
services:
  mysql:
    image: mysql
    container_name: music_player_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysqldb:/var/lib/mysql
    networks:
      - music-player-network
#  mysql-workbench:
#    image: openkbs/mysql-workbench
#    container_name: mysql-workbench
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Etc/UTC
#    volumes:
#      - mysqlworkbench:/config
#    ports:
#      - 3001:3000
#    cap_add:
#      - IPC_LOCK
#    depends_on:
#      - mysql
#    networks:
#      - music-player-network
volumes:
  mysqldb:
    driver: local
  mysqlworkbench:
    driver: local
networks:
  music-player-network:
    driver: bridge
    name: music-player-network


